x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
    - ./dados:/opt/bitnami/spark/dados
  env_file:
    - .env
  networks:
    - spark_flow

services:
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: ${SPARK_WORKER_CORES}
      SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY}
      SPARK_MASTER_URL: spark://spark-master:7077
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
      YARN_CONF_DIR: /opt/hadoop/etc/hadoop

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Defina a senha do root aqui
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - spark_flow

  job1:
    <<: *spark-common
    command: bin/spark-submit --master spark://spark-master:7077 --deploy-mode client /opt/bitnami/spark/jobs/job1.py
    depends_on:
      - spark-master
      - spark-worker

networks:
  spark_flow:
    driver: bridge
